version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'DBForTest'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_INITDB_SKIP_TZINFO: '1'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    expose:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/DBForTest
    volumes:
      - ./src:/usr/backend/src
    command: sh -c "/usr/wait-for-it.sh db:3306 -- npm run start:dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    expose:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./src:/usr/frontend/src

volumes:
  my-db:
